# -*- coding: utf-8 -*-
"""Sentimental_analysis_using_transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwUvX8Z8wXZOfeb8NGNnr_sZbpMJUgYh
"""

!pip install transformers

from transformers import pipeline

sentiment_pipeline = pipeline("sentiment-analysis")
texts = [
    "I love this phone 😍🔥",
    "This app is trash 😡💩",
    "Hmm 🤔 not sure about this one...",
    "That concert was lit 🔥🔥🔥",
]

results = sentiment_pipeline(texts)

for text, result in zip(texts, results):
    print(f"{text} => {result['label']} ({result['score']:.4f})")